### ISSUE TITLE
Limitations notePath

### ISSUE THREAD

**Issue by PidgeyL** [cristianvasquez/obsidian-lab#10]
Hello!

Loving the plug-in, though I'm having some issues with a limitation of the "notePath" argument. It seems it only returns the note name, not the full path, making it impossible to differentiate between notes with the same name (e.g /folder1/note, and /folder2/note), and finding the note requires an os.walk, rather than just use the notePath argument.
Is this a limitation of Obsidian, or could this be fixed?

Thanks!

KR,
Pidgey

**Comment by m-rau** [comment]
cannot confirm. Having 2 "Untitiled.md" the plugin yields
```
  {"vaultPath":"/Users/raum/Project/docs.test","notePath":"test1/Untitled.md"}
```
for the one and 
```
  {"vaultPath":"/Users/raum/Project/docs.test","notePath":"Untitled.md"}
```
for the other!

**Comment by PidgeyL** [comment]
I think I was misunderstanding some of the examples, my bad!
