### ISSUE TITLE
CORS policy error

### ISSUE THREAD

**Issue by chetachiezikeuzor** [cristianvasquez/obsidian-lab#2]
Hello! I just wanted to submit some issues I've been having with the plugin. Right now, it's been giving these errors. I'm still trying to understand CORS but as of right now, the error is a mystery to me. I would love to be able to use this plugin but unfortunately, it does not for me. I hope this issue helps in some way.
Thanks!

<img width="430" alt="Screen Shot 2021-06-19 at 2 28 02 PM" src="https://user-images.githubusercontent.com/79069364/122653980-119a3c00-d10e-11eb-9a1c-ab78c637b4e9.png">

<img width="420" alt="Screen Shot 2021-06-19 at 2 53 32 PM" src="https://user-images.githubusercontent.com/79069364/122654019-2080ee80-d10e-11eb-9645-f06de0ccad58.png">

**Comment by cristianvasquez** [comment]
Hello Chetachi! how looks like the python web application? 

Cors is a security mechanism that can be deactivated in the app, for example in the flask app: 

```python
####################################################################################
# Cors
####################################################################################
# Allows access to fetch at 'http://localhost:5000/' from origin 'app://obsidian.md'
obsidian_origin = "app://obsidian.md"
cors = CORS(app, origins=obsidian_origin)
app.config['CORS_HEADERS'] = 'Content-Type'
```

**Comment by cristianvasquez** [comment]
@chetachiezikeuzor I'll close the issue :)

**Comment by chetachiezikeuzor** [comment]
Yea sorry for not updating but everything is fine now! Thank you very much 😊.
